services:
  ldap_server:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Example Organization"
      LDAP_DOMAIN: "wani.example.com"
      LDAP_ADMIN_PASSWORD: "adminpass"
      LDAP_BASE_DN: "dc=wani,dc=example,dc=com"
      LDAP_TLS: "false"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - "389:389"
      - "636:636"
    networks:
      local-network:
        aliases:
          - ldap_server

  ldap_admin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap_server"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    networks:
      local-network:
        aliases:
          - ldap_admin

volumes:
  ldap_data:
  ldap_config:

networks:
  local-network:
