version: '3'
services:
  dust_dist:
    build:
      context: .
    working_dir: /home/pwn
    container_name: dust_dist
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9007:9999"
    entrypoint: /etc/init.sh
    restart: always
